debug: false
uuid: 441e1bc1-6772-46b8-85a3-ff3823dfb0a5
token_id: 2b7h5A04QZi3zjBM
token: l34Lt01A0DdT2QWQ0lbbwHccT8XwaYxsme6nhsL5OB4m7LO3NhPaz1150KHq7h60
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: true
    cert: /etc/letsencrypt/live/cn.skylikes.tech/fullchain.pem
    key: /etc/letsencrypt/live/cn.skylikes.tech/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://cp.skylikes.tech'
